//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2023_PM0202.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int receiptID { get; set; }
        public int clientID { get; set; }
        public int packageID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> statusID { get; set; }
        public int userID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Package Package { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
